version: '3.8'

services:
  gateway:
    container_name: gateway
    image: tittuvarghese/scalableservice:latest
    ports:
      - "8080:8080"
    command:
      - "./gateway"
    environment:
      - CUSTOMER_SERVICE_ADDRESS=customer-service:8080
      - PRODUCT_SERVICE_ADDRESS=product-service:8080
      - ORDER_SERVICE_ADDRESS=order-management-service:8080
      - OTEL_SERVICE_NAME="gateway"
      - OTEL_ENABLED=true
      - OTEL_COLLECTOR_URL="signoz-otel-collector:4318"
      - OTEL_INSECURE_MODE=true
  customer-service:
    container_name: customer-service
    image: tittuvarghese/scalableservice:latest
    command:
      - "./customer-service"
    environment:
      - DATABASE_URL=ecommerceuser:password@tcp(mariadb:3306)/ecommerce?charset=utf8mb4&parseTime=True&loc=Local
      - OTEL_SERVICE_NAME="customer-service"
      - OTEL_ENABLED=true
      - OTEL_COLLECTOR_URL="signoz-otel-collector:4317"
      - OTEL_INSECURE_MODE=true
      - SERVER_PORT=8080
    ports:
      - "8082:8080"
  product-service:
    container_name: product-service
    image: tittuvarghese/scalableservice:latest
    command:
      - "./product-service"
    environment:
      - DATABASE_URL=ecommerceuser:password@tcp(mariadb:3306)/ecommerce?charset=utf8mb4&parseTime=True&loc=Local
      - OTEL_SERVICE_NAME="product-service"
      - OTEL_ENABLED=true
      - OTEL_COLLECTOR_URL="signoz-otel-collector:4318"
      - OTEL_INSECURE_MODE=true
      - SERVER_PORT=8080
    ports:
      - "8083:8080"
  order-management-service:
    container_name: order-management-service
    image: tittuvarghese/scalableservice:latest
    command:
      - "./order-management-service"
    environment:
      - DATABASE_URL=ecommerceuser:password@tcp(mariadb:3306)/ecommerce?charset=utf8mb4&parseTime=True&loc=Local
      - OTEL_SERVICE_NAME="order-management-service"
      - OTEL_ENABLED=true
      - OTEL_COLLECTOR_URL="signoz-otel-collector:4317"
      - OTEL_INSECURE_MODE=true
      - SERVER_PORT=8080
    ports:
      - "8084:8080"
