version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: complexpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerceuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
#    restart: unless-stopped

volumes:
  mariadb-data:
    driver: local
